search:
  paths:
    - "app/controllers"
    - "app/helpers"
    - "app/presenters"
    - "app/views"

ignore_unused:
  - activerecord.*
  - date.*
  - product_request_mailer.*
  - rejection_mailer.*
  - simple_form.*
  - time.*
  - titles.*
  - welcome_mailer.*
