common: &default_settings
  app_name: "apps-gov-v2"
  license_key: "<%= ENV["NEW_RELIC_LICENSE_KEY"] %>"
  log_level: info
development:
  app_name: apps-gov-v2 (Development)
  <<: *default_settings
  developer_mode: true
test:
  <<: *default_settings
  monitor_mode: false
production:
  <<: *default_settings
staging:
  <<: *default_settings
  app_name: "apps-gov-v2 (Staging)"
